version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: ai-learning-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ai-learning-platform
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: